mockserver:
  bean:
    port: 1050

spring:
  application:
    name: PN-PORTFAT

pn:
  portfat:
    sqsQueue: ${AWS_SQS_URL}
    blobStorageBaseUrl: https://storage.portalefatturazione.pagopa.it
    filePathWhiteList: temp, portfatt, port-fatt
    basePathZipFiele: port-fat-zips
    zipExtension: .zip
    clientSafeStorageBasePath: ${PN_PORTFAT_SAFESTORAGEBASEURL}
    safeStorageCxId: ${PN_PORTFAT_SAFESTORAGECXID}

aws:
  region-code: ${AWS_REGIONCODE}
  profile-name: ${PN_AWS_PROFILE_NAME:default}
  endpoint-url: ${AWS_ENDPOINT_URL}
  dynamodbPrtFatTable: PortFatDownload

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: test
      secret-key: test