AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

Resources:
  # Internal queues
  PortFatRequestActionsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-portfat_request_actions'
        FifoQueue: true
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 1200
        MaxReceiveCount: 5
        HasDLQ: "true"
        QueueHasAlarm: "true"

   # Dynamo table
  PortFatDownloadTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PortFatDownload'
      AttributeDefinitions:
        - AttributeName: "downloadId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "downloadId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # Log group
  PortFatLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-portfat'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  # Log group
  EventFileReadyLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-portfat-eventFileReady-lambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:
  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PortFatLogGroup.Outputs.LogGroupName

  LambdaLogGroup:
    Value: !GetAtt EventFileReadyLambdaLogGroup.Outputs.LogGroupName

  # Dynamo table
  PortFatDownloadTableName:
    Description: Name of dynamodb table containing Downloads files
    Value: !Ref PortFatDownloadTable

  PortFatDownloadTableArn:
    Description: ARN of dynamodb table containing Downloads files
    Value: !GetAtt PortFatDownloadTable.Arn

  # Queue
  PortFatRequestActionsQueueName:
    Description: pn-portfat_request_actions queue name
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.QueueName

  PortFatRequestActionsQueueURL:
    Description: pn-portfat_request_actions queue URL
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.QueueURL

  PortFatRequestActionsQueueARN:
    Description: pn-portfat_request_actions queue ARN
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.QueueARN

  PortFatRequestActionsQueueAlarmARN:
    Description: pn-portfat_request_actions alarm ARN
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.SqsDLQAlarmArn

  PortFatRequestActionsQueueAgeAlarmARN:
    Description: pn-portfat_request_actions age alarm ARN
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.SqsAgeAlarmArn

  # Queue DLQ
  PortFatRequestActionsQueueDLQName:
    Description: pn-portfat_request_actions_DLQ queue name
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.DeadLetterQueueName

  PortFatRequestActionsQueueDLQURL:
    Description: pn-portfat_request_actions_DLQ queue URL
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.DeadLetterQueueURL

  PortFatRequestActionsQueueDLQARN:
    Description: pn-portfat_request_actions_DLQ queue ARN
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.DeadLetterQueueARN

  PortFatRequestActionsQueueDLQAlarmARN:
    Description: pn-portfat_request_actions_DLQ alarm ARN
    Value: !GetAtt PortFatRequestActionsQueue.Outputs.SqsDLQAlarmArn

  # Lambda functions
  EventFileReadyLambdaName:
    Description: Name of event file ready lambda
    Value: !Sub "${ProjectName}-portfat-eventFileReady-lambda"