logging:
  config: config/logback-local.xml
server:
  port: 8099

pn:
  env:
    runtime: DEVELOPMENT
  pn-portfat-queue:
#pn.env.runtime=PROD

# AWS specific configurations
aws:
  region-code: us-east-1
  profile-name: ${PN_AWS_PROFILE_NAME:default}
  endpoint-url: http://localhost:4566
